### ISSUE TITLE
Issue session rollback after some errors

### ISSUE THREAD

**Issue by geoslegend** [geopython/pywps#176]
# Description

After there is an error, if the pywps service receives new request, 
the error messages are shown as follows:

```
[pid 21389:tid 140700116551424] 2016-09-02 16:53:15,709 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
[pid 21389:tid 140700116551424] 2016-09-02 16:53:15,710 INFO sqlalchemy.engine.base.Engine INSERT INTO pywps_requests (uuid, pid, operation, version, time_start, time_end, identifier, message, percent_done, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
[pid 21389:tid 140700116551424] 2016-09-02 16:53:15,710 INFO sqlalchemy.engine.base.Engine ('4e206528-70e2-11e6-891d-ecb1d783f730', 21389, 'execute', '1.0.0', '2016-09-02 16:53:15.708929', None, 'OpenWPS:CV_VisualizeNonSeries', None, None, None)
[pid 21389:tid 140700116551424] 2016-09-02 16:53:15,710 INFO sqlalchemy.engine.base.Engine COMMIT
[pid 21389:tid 140700116551424] [remote xxx:30540] mod_wsgi (pid=21389): Exception occurred processing WSGI script '/xxx/pywps/wps.wsgi'.
[pid 21389:tid 140700116551424] [remote xxx:30540] Traceback (most recent call last):
[pid 21389:tid 140700116551424] [remote xxx:30540]   File "/xxx/python2.7/site-packages/werkzeug/wrappers.py", line 291, in application
[pid 21389:tid 140700116551424] [remote xxx:30540]     return f(*args[:-2] + (request,))(*args[-2:])
[pid 21389:tid 140700116551424] [remote xxx:30540]   File "/xxx/python2.7/site-packages/pywps-4.0.0rc1-py2.7.egg/pywps/app/Service.py", line 585, in __call__
[pid 21389:tid 140700116551424] [remote xxx:30540]     request_uuid
[pid 21389:tid 140700116551424] [remote xxx:30540]   File "/xxx/python2.7/site-packages/pywps-4.0.0rc1-py2.7.egg/pywps/app/Service.py", line 297, in execute
[pid 21389:tid 140700116551424] [remote xxx:30540]     tempdir = tempfile.mkdtemp(prefix='pywps_process_', dir=workdir)
[pid 21389:tid 140700116551424] [remote xxx:30540]   File "/xxx/python2.7/tempfile.py", line 333, in mkdtemp
[pid 21389:tid 140700116551424] [remote xxx:30540]     _os.mkdir(file, 0700)
[pid 21389:tid 140700116551424] [remote xxx:30540] OSError: [Errno 13] Permission denied: '/tmp/outputs/pywps_process_OyLFRX'
[pid 21388:tid 140700041606912] [remote xxx:65351] mod_wsgi (pid=21388): Exception occurred processing WSGI script '/xxx/pywps/wps.wsgi'.
[pid 21388:tid 140700041606912] [remote xxx:65351] Traceback (most recent call last):
[pid 21388:tid 140700041606912] [remote xxx:65351]   File "/xxx/python2.7/site-packages/werkzeug/wrappers.py", line 291, in application
[pid 21388:tid 140700041606912] [remote xxx:65351]     return f(*args[:-2] + (request,))(*args[-2:])
[pid 21388:tid 140700041606912] [remote xxx:65351]   File "/xxx/python2.7/site-packages/pywps-4.0.0rc1-py2.7.egg/pywps/app/Service.py", line 573, in __call__
[pid 21388:tid 140700041606912] [remote xxx:65351]     log_request(request_uuid, wps_request)
[pid 21388:tid 140700041606912] [remote xxx:65351]   File "/xxx/python2.7/site-packages/pywps-4.0.0rc1-py2.7.egg/pywps/dblog.py", line 65, in log_request
[pid 21388:tid 140700041606912] [remote xxx:65351]     session.commit()
[pid 21388:tid 140700041606912] [remote xxx:65351]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 811, in commit
[pid 21388:tid 140700041606912] [remote xxx:65351]     self.transaction.commit()
[pid 21388:tid 140700041606912] [remote xxx:65351]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 396, in commit
[pid 21388:tid 140700041606912] [remote xxx:65351]     self._assert_active(prepared_ok=True)
[pid 21388:tid 140700041606912] [remote xxx:65351]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 213, in _assert_active
[pid 21388:tid 140700041606912] [remote xxx:65351]     % self._rollback_exception
[pid 21388:tid 140700041606912] [remote xxx:65351] InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140700041606912 and this is thread id 140700158510848
```
# Environment
- operating system: CentOS 6.5 final
- Python version: 2.7.10
- PyWPS version: 4.0.0rc1 (cloned on 31 Aug 2016 13:46 UTC+09:00)
- source/distribution
  - [O] git clone
  - [ ] Debian
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify): 
- web server
  - [O] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 
# Steps to Reproduce

i) changing permission of output directory
ii) calling pywps service, then the first error message is shown as 'permission denied'
ii) re-calling pywps service, then the second error message is shown as 'InvalidRequestError' 
# Additional Information

The first error is no problem because I can solve that.

**Comment by jachym** [comment]
Well, the error log should be more readable, but from what I see there

```
...
[Fri Sep 02 16:53:15.711850 2016] [wsgi:error] [pid 21389:tid 140700116551424] [remote xxx.xxx.xxx.xxx:30540] OSError: [Errno 13] Permission denied: '/tmp/outputs/pywps_process_OyLFRX'
...
```

I would say, you do not have permissions (or the user, PyWPS is running under) to create new directory in /tmp/outputs

**Comment by geoslegend** [comment]
Hi, @jachym 
According to your comments, I am going to write the error messages more readable next time.
However, I had to include such error messages because I thought that you guys needed it in order to analyze more exact reason. And I already know permission problem. So I added the information into Additional Information section. I just would like to ask that if another error causes, the session rollback error is no problem? In other words, I guess that the pattern try/catch has any bugs.
Thank you.
FYI) I just modified error messages on my question more readable.

**Comment by jonas-eberle** [comment]
@jachym See the error message in the last line: 
`Original exception was: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140700041606912 and this is thread id 140700158510848`

Stackoverflow shows this explanation ("You may not be using threads explicitly, but mod_wsgi is, and you've defined a global session object") and solution: 
http://stackoverflow.com/a/34010159

**Comment by jachym** [comment]
@geoslegend please, your report was OK, my comment was regarding PyWPS: PyWPS should report error messages in more readable manner

**Comment by jachym** [comment]
@geoslegend @jonas-eberle so, do I understand it correctly, that moving from sqlite3 to postgres should solve the issue?

**Comment by geoslegend** [comment]
@jachym I guess so. Eventually, I think that it seems better to adopt DBMS such as postgres.

**Comment by jonas-eberle** [comment]
@geoslegend Jachym introduced SQLAlchemy to be able to switch to other DMBS, such as postgres. I assume postgres should work out of the box. Can you give it a try? You only need to adjust the parameters in the config file, correct @jachym?

**Comment by geoslegend** [comment]
@jachym @jonas-eberle I had just changed database connection string in the config file, but the error message occurred. I guess that the reason is different data type between sqlite and postgres.

* The error message
```
2016-09-07 01:22:15,989 INFO sqlalchemy.engine.base.Engine {}
2016-09-07 01:22:15,990 INFO sqlalchemy.engine.base.Engine ROLLBACK
[remote xxx:25908] mod_wsgi (pid=22320): Exception occurred processing WSGI script '/xxx/pywps/wps.wsgi'.
[remote xxx:25908] Traceback (most recent call last):
[remote xxx:25908]   File "/xxx/python2.7/site-packages/werkzeug/wrappers.py", line 291, in application
[remote xxx:25908]     return f(*args[:-2] + (request,))(*args[-2:])
[remote xxx:25908]   File "/xxx/python2.7/site-packages/pywps-4.0.0rc1-py2.7.egg/pywps/app/Service.py", line 573, in __call__
[remote xxx:25908]     log_request(request_uuid, wps_request)
[remote xxx:25908]   File "/xxx/python2.7/site-packages/pywps-4.0.0rc1-py2.7.egg/pywps/dblog.py", line 59, in log_request
[remote xxx:25908]     session = get_session()
[remote xxx:25908]   File "/xxx/python2.7/site-packages/pywps-4.0.0rc1-py2.7.egg/pywps/dblog.py", line 166, in get_session
[remote xxx:25908]     ProcessInstance.metadata.create_all(engine)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/schema.py", line 3829, in create_all
[remote xxx:25908]     tables=tables)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1917, in _run_visitor
[remote xxx:25908]     conn._run_visitor(visitorcallable, element, **kwargs)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1526, in _run_visitor
[remote xxx:25908]     **kwargs).traverse_single(element)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
[remote xxx:25908]     return meth(obj, **kw)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
[remote xxx:25908]     _is_metadata_operation=True)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/visitors.py", line 121, in traverse_single
[remote xxx:25908]     return meth(obj, **kw)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 767, in visit_table
[remote xxx:25908]     include_foreign_key_constraints=include_foreign_key_constraints
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 947, in execute
[remote xxx:25908]     return meth(self, multiparams, params)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
[remote xxx:25908]     return connection._execute_ddl(self, multiparams, params)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1004, in _execute_ddl
[remote xxx:25908]     compiled
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1191, in _execute_context
[remote xxx:25908]     context)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1386, in _handle_dbapi_exception
[remote xxx:25908]     exc_info
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 202, in raise_from_cause
[remote xxx:25908]     reraise(type(exception), exception, tb=exc_tb, cause=cause)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1184, in _execute_context
[remote xxx:25908]     context)
[remote xxx:25908]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 462, in do_execute
[remote xxx:25908]     cursor.execute(statement, parameters)
[remote xxx:25908] ProgrammingError: (psycopg2.ProgrammingError) type "blob" does not exist
[remote xxx:25908] LINE 4:  request BLOB NOT NULL, 
[remote xxx:25908]                  ^
[remote xxx:25908]  [SQL: '\\nCREATE TABLE pywps_stored_requests (\\n\\tuuid VARCHAR(255) NOT NULL, \\n\\trequest BLOB NOT NULL, \\n\\tPRIMARY KEY (uuid)\\n)\\n\\n']
```

**Comment by bstdenis** [comment]
Just to confirm, I also have this problem. This was not the case in RC1. This commit 5f579d4a353677e9b58375fbda9932dd9f4551e2 seem to have introduced the issue. On top of the InvalidRequestError mentioned above, my apache log is also complaining about:

```
[Tue Sep 06 17:56:19.488170 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477] mod_wsgi (pid=41): Exception occurred processing WSGI script '/var/www/html/wps/pywps.wsgi'.
[Tue Sep 06 17:56:19.488230 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477] Traceback (most recent call last):
[Tue Sep 06 17:56:19.488249 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.11.11-py2.7.egg/werkzeug/wrappers.py", line 291, in application
[Tue Sep 06 17:56:19.488628 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     return f(*args[:-2] + (request,))(*args[-2:])
[Tue Sep 06 17:56:19.488644 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "/usr/local/lib/python2.7/dist-packages/pywps-4.0.0rc2-py2.7.egg/pywps/app/Service.py", line 573, in __call__
[Tue Sep 06 17:56:19.488827 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     log_request(request_uuid, wps_request)
[Tue Sep 06 17:56:19.488844 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "/usr/local/lib/python2.7/dist-packages/pywps-4.0.0rc2-py2.7.egg/pywps/dblog.py", line 65, in log_request
[Tue Sep 06 17:56:19.488913 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     session.commit()
[Tue Sep 06 17:56:19.488929 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 811, in commit
[Tue Sep 06 17:56:19.489921 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     self.transaction.commit()
[Tue Sep 06 17:56:19.489940 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 398, in commit
[Tue Sep 06 17:56:19.489951 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     self._prepare_impl()
[Tue Sep 06 17:56:19.489959 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 378, in _prepare_impl
[Tue Sep 06 17:56:19.489967 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     self.session.flush()
[Tue Sep 06 17:56:19.489976 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2065, in flush
[Tue Sep 06 17:56:19.489984 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     self._flush(objects)
[Tue Sep 06 17:56:19.489992 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2183, in _flush
[Tue Sep 06 17:56:19.490000 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     transaction.rollback(_capture_exception=True)
[Tue Sep 06 17:56:19.490009 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
[Tue Sep 06 17:56:19.490467 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     compat.reraise(exc_type, exc_value, exc_tb)
[Tue Sep 06 17:56:19.490484 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2147, in _flush
[Tue Sep 06 17:56:19.490493 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     flush_context.execute()
[Tue Sep 06 17:56:19.490513 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 386, in execute
[Tue Sep 06 17:56:19.490727 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     rec.execute(self)
[Tue Sep 06 17:56:19.490743 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 545, in execute
[Tue Sep 06 17:56:19.490753 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     uow
[Tue Sep 06 17:56:19.490782 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 176, in save_obj
[Tue Sep 06 17:56:19.491182 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     mapper, table, insert)
[Tue Sep 06 17:56:19.491197 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 776, in _emit_insert_statements
[Tue Sep 06 17:56:19.491207 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     execute(statement, multiparams)
[Tue Sep 06 17:56:19.491218 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 947, in execute
[Tue Sep 06 17:56:19.491867 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     return meth(self, multiparams, params)
[Tue Sep 06 17:56:19.491887 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 262, in _execute_on_connection
[Tue Sep 06 17:56:19.493092 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     return connection._execute_clauseelement(self, multiparams, params)
[Tue Sep 06 17:56:19.493114 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1055, in _execute_clauseelement
[Tue Sep 06 17:56:19.493124 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     compiled_sql, distilled_params
[Tue Sep 06 17:56:19.493133 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1191, in _execute_context
[Tue Sep 06 17:56:19.493140 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     context)
[Tue Sep 06 17:56:19.493148 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1386, in _handle_dbapi_exception
[Tue Sep 06 17:56:19.493156 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     exc_info
[Tue Sep 06 17:56:19.493163 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 202, in raise_from_cause
[Tue Sep 06 17:56:19.493302 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     reraise(type(exception), exception, tb=exc_tb, cause=cause)
[Tue Sep 06 17:56:19.493318 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1184, in _execute_context
[Tue Sep 06 17:56:19.493327 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     context)
[Tue Sep 06 17:56:19.493338 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 462, in do_execute
[Tue Sep 06 17:56:19.493651 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477]     cursor.execute(statement, parameters)
[Tue Sep 06 17:56:19.493744 2016] [wsgi:error] [pid 41:tid 139725325768448] [remote 172.17.0.1:59477] OperationalError: (sqlite3.OperationalError) no such table: pywps_requests [SQL: u'INSERT INTO pywps_requests (uuid, pid, operation, version, time_start, time_end, identifier, message, percent_done, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('36fe63aa-745b-11e6-968d-0242ac110002', 41, u'describeprocess', u'1.0.0', '2016-09-06 17:56:19.486979', None, u'mywpsprocess', None, None, None)]
```

**Comment by jachym** [comment]
nice :-/

**Comment by jachym** [comment]
@bstdenis strange thing, there is no pywps_request table used in pywps code (fresh version) - could you please try current master ?

**Comment by jachym** [comment]
@geoslegend which database are you testing? sqlite3? postgres? something else? Could you please pass your database connection configuration value (without passwords of course) ?

**Comment by geoslegend** [comment]
@jachym It was tested using the connection string, 'database=postgresql://xxx:xxx@xxx:5432/dev', in wps.cfg.

**Comment by bstdenis** [comment]
@jachym just to follow up, there is a pywps_requests table, it's created as a combination of the default logging prefix CONFIG.set('logging', 'prefix', 'pywps_') in configuration.py and __tablename__ = '{}requests'.format(_tableprefix) in dblog.py

However, I'm not sure if my issue is really related to the original one in this report. I did get the session rollback error around the same time though, but I can't reproduce it now. On my end, the database is the default 'sqlite:///:memory:'.

**Comment by jachym** [comment]
good news: I've just installed PyWPS-4 into fresh (vagrant) server and did reproduce it!! I can go on now

**Comment by jachym** [comment]
Folks, could you please test following commit ? https://github.com/geopython/pywps/pull/204/commits ?It should fix the issue - tested with both (sqlite:////full/path.db and :memory:), seems to be ok

**Comment by jachym** [comment]
I hope,  #204 fixes this - feel free to re-open, if not
