### ISSUE TITLE
TypeError when file suffix is empty

### ISSUE THREAD

**Issue by KolesovDmitry** [geopython/pywps#288]
# Description
This function (https://github.com/geopython/pywps/blob/develop/pywps/app/Service.py#L686) raises TypeError:

```
Traceback (most recent call last):
  File "/home/klsvd/laboro/processing/venv/src/pywps/pywps/app/Service.py", line 609, in __call__
    request_uuid
  File "/home/klsvd/laboro/processing/venv/src/pywps/pywps/app/Service.py", line 307, in execute
    response = self._parse_and_execute(process, wps_request, uuid)
  File "/home/klsvd/laboro/processing/venv/src/pywps/pywps/app/Service.py", line 339, in _parse_and_execute
    inpt, wps_request.inputs[inpt.identifier])
  File "/home/klsvd/laboro/processing/venv/src/pywps/pywps/app/Service.py", line 498, in create_complex_inputs
    complex_data_handler(data_input, inpt)
  File "/home/klsvd/laboro/processing/venv/src/pywps/pywps/app/Service.py", line 403, in href_handler
    extension=_extension(complexinput))
  File "/home/klsvd/laboro/processing/venv/src/pywps/pywps/app/Service.py", line 696, in _build_input_file_name
    dir=workdir)[1]
  File "/usr/lib/python2.7/tempfile.py", line 308, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 237, in _mkstemp_inner
    file = _os.path.join(dir, pre + name + suf)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

# Environment

- operating system: Linux
- Python version: 2.7
- PyWPS version: source from github repo

# Steps to Reproduce
It happens if two different URLs create temp files with the same filename without extension. 

1. Create Process with 2 inputs, for example:
```
class Selector(Process):
    def __init__(self, grass_location):
        inputs = [
            ComplexInput('input1', 'input1', supported_formats=[Format(FORMATS.GEOJSON.mime_type)]),
            ComplexInput('input2', 'input2', supported_formats=[Format(FORMATS.GEOJSON.mime_type)]),
        ]
        outputs = [
            ComplexOutput('result', 'result', supported_formats=[Format(FORMATS.SHP.mime_type)])
        ]
        super(Selector, self).__init__(
            self._handler,
            identifier='Selector',
            version='0.1',
            title="Selector",
            abstract='Get data from Input1 overlaped with data in Input2',
            profile='',
            inputs=inputs,
            outputs=outputs,
            store_supported=True,
            status_supported=True,
            grass_location=grass_location
        )
    # dummy handler
    def _handler(self, request, response):
        return response
```

2. Pass to the process request with 2 urls, for example:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<wps:Execute service="WPS" version="1.0.0" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 ../wpsExecute_request.xsd">
    <ows:Identifier>Selector</ows:Identifier>
    <wps:DataInputs>
        <wps:Input>
            <ows:Identifier>input1</ows:Identifier>
            <ows:Title>inpit1</ows:Title>
            <wps:Reference xlink:href="https://kolesov.nextgis.com/api/resource/86/geojson"/>
        </wps:Input>
        <wps:Input>
            <ows:Identifier>input2</ows:Identifier>
            <ows:Title>input2</ows:Title>
            <wps:Reference xlink:href="https://kolesov.nextgis.com/api/resource/86/geojson"/>
        </wps:Input>
    </wps:DataInputs>
    <wps:ResponseForm>
       <wps:ResponseDocument status="true" storeExecuteResponse="true">
         <wps:Output asReference="true">
           <ows:Identifier>result</ows:Identifier>
         </wps:Output>
       </wps:ResponseDocument>
    </wps:ResponseForm>
</wps:Execute>
```
The URL (https://kolesov.nextgis.com/api/resource/86/geojson) links 'geojson' file, so ```input1``` and ```input2``` produse temp files with equal names.

# Additional Information

1. if file_name is a name without extension, then the line https://github.com/geopython/pywps/blob/develop/pywps/app/Service.py#L690 generates pair: (prefix=file_name, suffix='')
2. The next line https://github.com/geopython/pywps/blob/develop/pywps/app/Service.py#L691 evaluates ```suffix = '' or None```, therefore suffix==None.
3. Finally ```tempfile.mkstemp``` https://github.com/geopython/pywps/blob/develop/pywps/app/Service.py#L698 concatenates ```None+string```, so this causes the error.

# How to fix
Replace https://github.com/geopython/pywps/blob/develop/pywps/app/Service.py#L691 by the next line:
```
suffix = suffix or extension or ''
```

**Comment by jorgejesus** [comment]
Issue only affects python2.7
