### ISSUE TITLE
BoundingBox implementation is broken

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#405]
# Description

I tried to use the `bbox` and I run into the following exception:

```
2018-09-10 14:11:06,149] [INFO] line=306 module=Service Request: execute
2018-09-10 14:11:06,160] [ERROR] line=45 module=exceptions Exception: code: 500, locator: No applicable error code, please check error log., description: 
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/emu/lib/python3.6/site-packages/pywps/app/Service.py", line 332, in call
    raise e
  File "/usr/local/anaconda3/envs/emu/lib/python3.6/site-packages/pywps/app/Service.py", line 325, in call
    request_uuid
  File "/usr/local/anaconda3/envs/emu/lib/python3.6/site-packages/pywps/app/Service.py", line 81, in execute
    return self._parse_and_execute(process, wps_request, uuid)
  File "/usr/local/anaconda3/envs/emu/lib/python3.6/site-packages/pywps/app/Service.py", line 130, in _parse_and_execute
    inpt, request_inputs)
  File "/usr/local/anaconda3/envs/emu/lib/python3.6/site-packages/pywps/app/Service.py", line 273, in create_bbox_inputs
    newinpt.data = [datainput.minx, datainput.miny,
AttributeError: 'dict' object has no attribute 'minx'

```
# Environment

- operating system:
- Python version:
- PyWPS version: pre 4.2 on master
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

I'm using the bbox process in [Emu](https://github.com/bird-house/emu/blob/master/emu/processes/wps_bbox.py).

See bbox test:
https://github.com/bird-house/emu/blob/master/tests/test_wps_bbox.py

# Additional Information

**Comment by cehbrecht** [comment]
Fixed by PR #551
